### ISSUE TITLE
Incorrect block discovery algorithm

### ISSUE THREAD

**Issue by gandrewstone** [hashingitcom/bitcoin_traffic_bulletin#1]
Judging by the red line in the graph "Probability for Confirmation..." I think that you're using the wrong algorithm to generate block discovery probabilities.

You want the Poisson process equation which is a decreasing exponential p = lambda*e^(-lambda*t), not the Poisson probability equation.

We are agreed that the chance of finding a block is exactly the same at any second T, right?  Let's call that probability P.

Given that, think of it this way.  The chance of finding the next block 1 second after is therefore P.  The chance of finding the next block 2 seconds after is the probability that you DIDN'T find a block 1 second after \* the probability you DID find one 2 seconds after (P), so (1-P)*P.  And so on...

So there is a big difference between the chance of finding a block on second S, compared to finding the NEXT block on second S.  The first is P, the second must take into account all the time from 0 to S-1.

**Comment by dave-hudson** [comment]
Thanks for the message - I agree that the PP equation you quoted is the right one to give the probability at any time t, given a rate lambda. This in turn gives rise to a CDF that has an exponential distribution of interarrival times, and it's this that's being used to generate the interarrival times in the simulation.

I just checked a number of, hopefully, independent sources and all agree on this point - including one of my old numeric analysis textbooks from the late 80s to avoid any Google biases :-). Here's one such reference: http://transp-or.epfl.ch/courses/OptSim2012/slides/05b-poisson.pdf (slide 8 and 9 are the most relevant here).

I ought to get an hour or two over the weekend and will double check the implementation though. I guess it's certainly possible that the implementation may have some unforseen ill-condition problems, although earlier simulations I did with dramatically more precision (but were thus a lot slower) didn't show any interesting differences.

As regards the second part of your observation each phase of the simulation is independent of the previous one (since we're talking about a memoryless process). The probability associated with finding a second block (ignoring difficulty changes) is, ideally, independent of anything related to the first block that preceded it. In practice latencies will have some impact which is why the real network sees orphans but I've not attempted to model them here. Consequently the probabilities produced by the model for finding block n at time t vs block n+1 at time t should be reflected correctly.

Regards,
Dave

**Comment by gandrewstone** [comment]
Hmm... I'm having a hard time relating what you just said to my critique.

Your red line looks like the CDF, but your blue like doesn't look at all like the PDF.

https://cloud.sagemath.com/projects/f16b2143-b338-4862-a079-9b8cea933247/files/2015-12-18-090813.sagews

Maybe the confusion here is in the english -- in your description of what the blue line actually represents.

**Comment by dave-hudson** [comment]
Ah, now I think I understand the confusion!

The CDF shown here looks, superficially, similar to the one I think you're expecting to see which would represent the CDF for block finding, but that's not what either of these represent, although in the limit with a lightly loaded network they're pretty close. This also means I didn't explain the probability sufficiently well (it's an artifact of the way the simulation works and represents the probability of an event hitting a logarithmically-sized bucket)!

We're effectively dealing with the hitchhiker's paradox but in a progressively more complex form (I only found this reference earlier today though which is why I didn't mention it in my article).

I'm not sure if you noticed or not, but the chart does not have a nice smooth line and that's because it's derived from a very large number of simulations rather than an attempt to generate an analytical result (there are a lot of simulations though as the intent was to make the lines as smooth as possible without taking a week to run the simulations).

Each simulation trace is based on 100k individual simulations of mining 1008 blocks (a nominal week). The simulation does something that may be non-obvious. The first confirmation time for a transaction is derived from the time that the transaction first hits the network to the time it's mined into a block. Again this is a slightly optimistic assumption in that there's latency from a transaction being broadcast to someone trying to mine it, but what this means is that a transaction that's broadcast 1 second before a block is mined, but for which there was capacity in the block is deemed to take 1 second to get a first confirmation. This is independent of how long the block took to find. Let's say it might have taken 20 minutes to find that block. In that same block we might also have a transaction that was broadcast 1 second after the previous block, in which case that other transaction will have taken 1199 seconds to get a first confirmation.

What I'll do (sometime this weekend) is patch the simulation so that it reflects the probabilities in a more intuitive form! Showing the bucketized versions is useful from the perspective of understanding the simulation but isn't very satisfying from a mathematical perspective.

I'll be more than happy to cite your comments (they're the first useful feedback I've had here) if you'd like to send me whatever details you'd like me to use.

Cheers,
Dave

**Comment by dave-hudson** [comment]
Forgot to note - I'll be updating the "waiting for blocks" article too - that has the same simulation artifact!
